POST http://localhost:8080/
Tus-Resumeable: 1.0.0
Upload-Length: 12
Upload-Metadata: filename dGVzdC50eHQ=

###
POST http://localhost:8080/
Tus-Resumable: 1.0.0
Upload-Length: 0
Upload-Metadata: filename test.txt

###
PATCH http://localhost:8080/bf9c0d74-e8a0-41cd-9871-746f93c489b2
Tus-Resumable: 1.0.0
Upload-Offset: 9
Content-Type: application/offset+octet-stream

< ./test.txt

###
HEAD http://localhost:8080/bf9c0d74-e8a0-41cd-9871-746f93c489b2
Tus-Resumable: 1.0.0

// HEAD를 통해 offset 부터 다시